image: docker:latest

variables:
  # This should be set by docker image already, just to be sure...
  DOCKER_HOST: tcp://docker:2375
  # Use overlayfs driver for better performance
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

services:
  - name: docker:dind
    command: ["--insecure-registry", "gitlab.toradex.int:4567"]

before_script:
  - docker info

stages:
  - build-base
  - build-weston
  - build-shell
  - deploy

# Docker image builds
#
# Build the Docker images  specificd in DOCKERFILE_FOLDER/IMAGE_NAME and push
# it to Gitlab's internal Docker registry
.docker-build:
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -f ${DOCKERFILE_FOLDER}Dockerfile -t ${CI_REGISTRY_IMAGE}/${IMAGE_NAME} ${DOCKERFILE_FOLDER}
    - docker push ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}

docker-build-base:
  extends: .docker-build
  variables:
    IMAGE_NAME: arm32v7-debian-base:buster-${CI_COMMIT_REF_SLUG}
    DOCKERFILE_FOLDER: "base/"
  stage: build-base

docker-build-weston:
  extends: .docker-build
  variables:
    IMAGE_NAME: arm32v7-debian-weston:buster-${CI_COMMIT_REF_SLUG}
    DOCKERFILE_FOLDER: "weston/"
  stage: build-weston

docker-build-shell:
  extends: .docker-build
  variables:
    IMAGE_NAME: arm32v7-debian-shell:buster-${CI_COMMIT_REF_SLUG}
    DOCKERFILE_FOLDER: "shell/"
  stage: build-shell

# Docker deploy jobs
#
# Make sure DOCKER_HUB_USER/DOCKER_HUB_PW is properly set in the project
# specific Gitlab CI settings.
.docker-deploy:
  before_script:
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PW
  stage: deploy
  when: manual
  script:
    - docker pull ${CI_REGISTRY_IMAGE}/${IMAGE_NAME}
    - docker tag ${CI_REGISTRY_IMAGE}/${IMAGE_NAME} ${DOCKER_HUB_USER}/${IMAGE_NAME}
    - docker push ${DOCKER_HUB_USER}/${IMAGE_NAME}

docker-deploy-base:
  extends: .docker-deploy
  variables:
    IMAGE_NAME: arm32v7-debian-base:buster-${CI_COMMIT_REF_SLUG}

docker-deploy-weston:
  extends: .docker-deploy
  variables:
    IMAGE_NAME: arm32v7-debian-weston:buster-${CI_COMMIT_REF_SLUG}

docker-deploy-shell:
  extends: .docker-deploy
  variables:
    IMAGE_NAME: arm32v7-debian-shell:buster-${CI_COMMIT_REF_SLUG}
