image: docker:latest

variables:
  # Use overlayfs driver for better performance
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker login -u torizon -p $DOCKER_HUB_PW

docker-build:
  stage: build
  script:
    - ./build.sh build
    - ./build.sh deploy

